# Introduction to Python
---
## Numpy
NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists.

- Numpy Array 
- Matrix
- Slice/Indexing Numpy Array

### Numpy Array

In [1]:
import numpy as np

In [2]:
average_age = 21

age = [23,24,26,18,21]
names = ['Raj','Ram','Rahul','Prashant','Tanvi']

print(age)
print(names)

[23, 24, 26, 18, 21]
['Raj', 'Ram', 'Rahul', 'Prashant', 'Tanvi']


#### List to Array

In [3]:
age = np.array(age)
age

array([23, 24, 26, 18, 21])

In [4]:
names = np.array(names)
names

array(['Raj', 'Ram', 'Rahul', 'Prashant', 'Tanvi'], dtype='<U8')

### Matrix

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np_matrix = np.array(my_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Slicing/Indexing

In [7]:
age

array([23, 24, 26, 18, 21])

In [8]:
age[0]

23

In [9]:
age[1:4]

array([24, 26, 18])

#### Broadcasting
- Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [10]:
age = np.array([23,24,26,18,21])
age

array([23, 24, 26, 18, 21])

In [11]:
# Can be sorted too
age.sort()
age

array([18, 21, 23, 24, 26])

In [12]:
age[0:2] = 100
age

array([100, 100,  23,  24,  26])

In [13]:
# If done on list - error
age_list = [23,24,26,18,21]
age_list[0:2] = 100

TypeError: can only assign an iterable

#### Often used to replace missing values or data cleaning

In [14]:
average_age

21

In [15]:
age[0:2] = average_age
age

array([21, 21, 23, 24, 26])