# Introduction to Python
---
## Numpy In-built Functions

- arange (similar to range())
- zeros()
- linspace()
- eye()
- reshape()

### arange

In [1]:
import numpy as np

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros()

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### linspace()

In [5]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [6]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

### eye()

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### reshape

In [14]:
arr = np.arange(9)
random_arr = np.random.randint(0,10,9)

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
random_arr

array([9, 6, 7, 5, 2, 0, 6, 9, 3])

In [12]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
random_arr.reshape(3,3)

array([[9, 6, 7],
       [5, 2, 0],
       [6, 9, 3]])