# Introduction to Python
---
## Numpy Selection and Summary

- selection
- summary functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(25)
random_arr = np.random.randint(0,50,20)

### selection

In [3]:
random_arr

array([31, 15, 12,  7, 32, 35, 17,  7, 48, 29, 12, 13, 10, 34,  7, 27,  7,
       42, 43, 16])

In [4]:
random_arr > 25

array([ True, False, False, False,  True,  True, False, False,  True,
        True, False, False, False,  True, False,  True, False,  True,
        True, False])

In [5]:
random_arr[random_arr > 25]

array([31, 32, 35, 48, 29, 34, 27, 42, 43])

#### With a variable - treat outliers/missing values

In [6]:
avg_random = random_arr.mean()
avg_random

22.2

In [7]:
random_arr[random_arr > avg_random]

array([31, 32, 35, 48, 29, 34, 27, 42, 43])

### Summary Functions

In [8]:
random_arr.max()

48

In [9]:
random_arr.min()

7

In [10]:
random_arr.mean()

22.2

In [11]:
random_arr.argmax()

8

In [12]:
random_arr.argmin()

3